apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/db-f/ros-comm-msgs:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/db-f/ros-comm-msgs:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: ros-comm-msgs
        chartPath: charts/ros-comm-msgs
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/db-f/ros-comm-msgs'
          image.tag: '{{.DIGEST_HEX}}'